/*
 * generated by Xtext 2.17.0
 */
package de.dc.javafx.mm.lang


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MmDslStandaloneSetup extends MmDslStandaloneSetupGenerated {

	def static void doSetup() {
		new MmDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
