/*
 * generated by Xtext 2.17.0
 */
package de.dc.javafx.mm.lang


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class MmDslRuntimeModule extends AbstractMmDslRuntimeModule {
}
