/*
 * generated by Xtext 2.17.0
 */
package de.dc.javafx.mm.lang.parser.antlr;

import com.google.inject.Inject;
import de.dc.javafx.mm.lang.parser.antlr.internal.InternalMmDslParser;
import de.dc.javafx.mm.lang.services.MmDslGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class MmDslParser extends AbstractAntlrParser {

	@Inject
	private MmDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMmDslParser createParser(XtextTokenStream stream) {
		return new InternalMmDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "EmfModel";
	}

	public MmDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MmDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
