/**
 * generated by Xtext 2.17.0
 */
package de.dc.javafx.mm.lang;

import de.dc.javafx.mm.lang.MmDslStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class MmDslStandaloneSetup extends MmDslStandaloneSetupGenerated {
  public static void doSetup() {
    new MmDslStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
