/**
 * generated by Xtext 2.17.0
 */
package de.dc.javafx.mm.lang;

import de.dc.javafx.mm.lang.AbstractMmDslRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class MmDslRuntimeModule extends AbstractMmDslRuntimeModule {
}
