/**
 * generated by Xtext 2.17.0
 */
package de.dc.javafx.mm.lang.validation;

import de.dc.javafx.mm.lang.validation.AbstractMmDslValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class MmDslValidator extends AbstractMmDslValidator {
}
