/**
 * generated by Xtext 2.17.0
 */
package de.dc.javafx.mm.lang.ui.labeling;

import com.google.inject.Inject;
import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

/**
 * Provides labels for EObjects.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
@SuppressWarnings("all")
public class MmDslLabelProvider extends DefaultEObjectLabelProvider {
  @Inject
  public MmDslLabelProvider(final AdapterFactoryLabelProvider delegate) {
    super(delegate);
  }
}
