/**
 * generated by Xtext 2.17.0
 */
package de.dc.javafx.mm.lang.ide;

import de.dc.javafx.mm.lang.ide.AbstractMmDslIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class MmDslIdeModule extends AbstractMmDslIdeModule {
}
