/**
 * generated by Xtext 2.17.0
 */
package de.dc.javafx.mm.lang.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import de.dc.javafx.mm.lang.MmDslRuntimeModule;
import de.dc.javafx.mm.lang.MmDslStandaloneSetup;
import de.dc.javafx.mm.lang.ide.MmDslIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class MmDslIdeSetup extends MmDslStandaloneSetup {
  @Override
  public Injector createInjector() {
    MmDslRuntimeModule _mmDslRuntimeModule = new MmDslRuntimeModule();
    MmDslIdeModule _mmDslIdeModule = new MmDslIdeModule();
    return Guice.createInjector(Modules2.mixin(_mmDslRuntimeModule, _mmDslIdeModule));
  }
}
