/*
 * generated by Xtext 2.17.0
 */
package de.dc.javafx.mm.lang.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMmDslScopeProvider extends DelegatingScopeProvider {
}
