/**
 * generated by Xtext 2.17.0
 */
package de.dc.javafx.mm.lang.scoping;

import de.dc.javafx.mm.lang.scoping.AbstractMmDslScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class MmDslScopeProvider extends AbstractMmDslScopeProvider {
}
