/*
 * generated by Xtext 2.17.0
 */
package de.dc.javafx.mm.lang.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class MmDslUiModule extends AbstractMmDslUiModule {
}
