/*
 * generated by Xtext 2.17.0
 */
package de.dc.javafx.mm.lang.ui.tests;

import com.google.inject.Injector;
import de.dc.javafx.mm.lang.ui.internal.LangActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MmDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return LangActivator.getInstance().getInjector("de.dc.javafx.mm.lang.MmDsl");
	}

}
